[tools]
rust = "1.90.0"
node = "24"
pnpm = "10"
lefthook = "latest"
"github:crate-ci/typos" = "latest"

[env]
CARGO_TERM_COLOR = "always"

[tasks."dev:be"]
run = "cargo run --bin server"
dir = "backend"

[tasks."dev:fe"]
run = "pnpm dev"
dir = "frontend"

[tasks."check:be"]
dir = "backend"
run = [
  "cargo fmt --all -- --check",
  "cargo clippy --all-targets --all-features -- -D warnings",
  "typos .. --exclude ../frontend --exclude Cargo.lock",
  "cargo check --all-targets --all-features",
  "cargo test --workspace",
]

[tasks."check:fe"]
dir = "frontend"
run = [
  "pnpm format:check",
  "pnpm lint",
  "typos . --exclude pnpm-lock.yaml",
  "pnpm typecheck",
  "pnpm build",
  "pnpm test",
]
