apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fullstack-template.fullname" . }}-frontend
  labels:
    app: {{ include "fullstack-template.fullname" . }}-frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "fullstack-template.fullname" . }}-frontend
  template:
    metadata:
      labels:
        app: {{ include "fullstack-template.fullname" . }}-frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.image.frontend.repository }}:{{ .Values.image.frontend.tag }}"
          imagePullPolicy: {{ .Values.image.frontend.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.frontend.port }}
              name: http
          env:
            - name: NEXT_PUBLIC_API_URL
              value: "/api/v1"
            - name: AUTH_OIDC_ID
              value: {{ .Values.env.oidcClientId | quote }}
            - name: AUTH_OIDC_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "fullstack-template.fullname" . }}-secrets
                  key: oidc_client_secret
            - name: AUTH_OIDC_ISSUER
              value: {{ .Values.env.oidcIssuerUrl | quote }}
            - name: NEXTAUTH_URL
              value: "https://{{ .Values.ingress.host }}"
            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "fullstack-template.fullname" . }}-secrets
                  key: nextauth_secret
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 15
          resources:
            {{- toYaml .Values.resources.frontend | nindent 12 }}
