apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullstack-template.fullname" . }}-frontend
  labels:
    app: {{ include "fullstack-template.fullname" . }}-frontend
spec:
  type: {{ .Values.service.frontend.type }}
  ports:
    - port: {{ .Values.service.frontend.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "fullstack-template.fullname" . }}-frontend
