apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fullstack-template.fullname" . }}-secrets
  labels:
    app: {{ include "fullstack-template.fullname" . }}
type: Opaque
data:
  database_url: {{ .Values.secrets.databaseUrl | b64enc | quote }}
  oidc_client_secret: {{ .Values.secrets.oidcClientSecret | b64enc | quote }}
  nextauth_secret: {{ .Values.secrets.nextauthSecret | b64enc | quote }}
